server:
  port: 8090
  
---
# api-gateway instance when used on Docker
spring:
  profiles: docker

# Define the port where the API gateway server would be running. This could always be port 8080
# since each docker container has it's own IP
server:
  port: 8080  
